import os

DATA_LOC = os.path.join(os.getcwd(),"npsubjects") #complete data folder

SPLIT_JSON_LOC = os.path.join(os.getcwd(),"tfp", "config", "split.json")

##file that contain labels generated by parcing cmu website
LABEL_JSON_LOC = os.path.join(os.getcwd(),"tfp", "config", "label.json")

PARENT_LIMBS = {
        21 : [16, 15, 1, 2, 3, 1, 5, 6, 14, 8, 9, 14, 11, 12, 14, 14, 1, 4, 7, 10, 13],
        15 : [0, 0, 1, 2, 3, 1, 5, 6, 1, 0, 9, 10, 0, 12,13]
        }


##Indexes of joint for 21 joint skeleton from total 31 joints
JOINT_INDEX = {
			21 : [0,1,2,3,4,6,7,8,9,11,13,15,16,17,18,20,21,24,25,27,28],
			15 : [0,1,2,3,6,7,8,13,16,17,18,20,24,25,27]
		}

JOINT_LABELS = {
            21: [
                "pelvis",
                "left_hip",
                "left_knee",
                "left_ankle",
                "left_foot",
                "right_hip",
                "right_knee",
                "right_ankle",
                "right_foot",
                "spine",
                "bottom_neck",
                "bottom_head",
                "head_top",
                "left_shoulder",
                "left_elbow",
                "left_waist",
                "left_hand",
                "right_shoulder",
                "right_elbow",
                "right_wrist",
                "right_hand"
            ]
        }

LIMB_RATIOS = {
                21 : [2.0, 2.5,
                       1.37, 2.8, 2.4,
                       1.37, 2.8, 2.4,
                       1.05, 4.2, 3.6,
                       1.05, 4.2, 3.6,
                       0, 2.25, 0.8,
                       1.2, 1.2,
                       2.0, 2.0]
            }
ROOT_LIMB = {
            21: 14
        }
HEAD_LIMB = {
            21:0
        }
